//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactFormWithMultiLanguageValidation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormField
    {
        public int Id { get; set; }
        public string SubmitTR { get; set; }
        public string SubmitEN { get; set; }
        public string ContactTR { get; set; }
        public string ContactEN { get; set; }
        public string DescriptionTR { get; set; }
        public string DescriptionEN { get; set; }
    }
}
